version: '3'
services:
  api:
    container_name: flask-container
    build: .
    depends_on:
      - postgres
    entrypoint: python app.py
    env_file: .env
    ports:
      - '5000:5000'

  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    env_file: .env
    expose:
      - '5432'
    ports:
      - '5433:5432'
    restart: always

